using System;

namespace SuperHot
{
	internal static class Instruct
	{
internal static Instruction Addc() { throw new InvalidOperationException(); }
internal static Instruction Add() { throw new InvalidOperationException(); }
internal static Instruction Addv() { throw new InvalidOperationException(); }
internal static Instruction And_b() { throw new InvalidOperationException(); }
internal static Instruction And() { throw new InvalidOperationException(); }
internal static Instruction Bf_s() { throw new InvalidOperationException(); }
internal static Instruction Bf() { throw new InvalidOperationException(); }
internal static Instruction Braf() { throw new InvalidOperationException(); }
internal static Instruction Bra() { throw new InvalidOperationException(); }
internal static Instruction Bsrf() { throw new InvalidOperationException(); }
internal static Instruction Bsr() { throw new InvalidOperationException(); }
internal static Instruction Bt_s() { throw new InvalidOperationException(); }
internal static Instruction Bt() { throw new InvalidOperationException(); }
internal static Instruction Clrmac() { throw new InvalidOperationException(); }
internal static Instruction Clrt() { throw new InvalidOperationException(); }
internal static Instruction CmpEq() { throw new InvalidOperationException(); }
internal static Instruction CmpGe() { throw new InvalidOperationException(); }
internal static Instruction CmpGt() { throw new InvalidOperationException(); }
internal static Instruction CmpHi() { throw new InvalidOperationException(); }
internal static Instruction CmpHs() { throw new InvalidOperationException(); }
internal static Instruction CmpPl() { throw new InvalidOperationException(); }
internal static Instruction CmpPz() { throw new InvalidOperationException(); }
internal static Instruction CmpStr() { throw new InvalidOperationException(); }
internal static Instruction Div0s() { throw new InvalidOperationException(); }
internal static Instruction Div0u() { throw new InvalidOperationException(); }
internal static Instruction Div1() { throw new InvalidOperationException(); }
internal static Instruction Dmuls_l() { throw new InvalidOperationException(); }
internal static Instruction Dmulu_l() { throw new InvalidOperationException(); }
internal static Instruction Dt() { throw new InvalidOperationException(); }
internal static Instruction Exts_b() { throw new InvalidOperationException(); }
internal static Instruction Exts_w() { throw new InvalidOperationException(); }
internal static Instruction Extu_b() { throw new InvalidOperationException(); }
internal static Instruction Extu_w() { throw new InvalidOperationException(); }
internal static Instruction Fabs() { throw new InvalidOperationException(); }
internal static Instruction Fadd() { throw new InvalidOperationException(); }
internal static Instruction FcmpEq() { throw new InvalidOperationException(); }
internal static Instruction FcmpGt() { throw new InvalidOperationException(); }
internal static Instruction Fdiv() { throw new InvalidOperationException(); }
internal static Instruction Fldi0() { throw new InvalidOperationException(); }
internal static Instruction Fldi1() { throw new InvalidOperationException(); }
internal static Instruction Flds() { throw new InvalidOperationException(); }
internal static Instruction Float() { throw new InvalidOperationException(); }
internal static Instruction Fmac() { throw new InvalidOperationException(); }
internal static Instruction Fmov() { throw new InvalidOperationException(); }
internal static Instruction Fmul() { throw new InvalidOperationException(); }
internal static Instruction Fneg() { throw new InvalidOperationException(); }
internal static Instruction Fsts() { throw new InvalidOperationException(); }
internal static Instruction Fsub() { throw new InvalidOperationException(); }
internal static Instruction Ftrc() { throw new InvalidOperationException(); }
internal static Instruction Jmp() { throw new InvalidOperationException(); }
internal static Instruction Jsr() { throw new InvalidOperationException(); }
internal static Instruction Ldc_l() { throw new InvalidOperationException(); }
internal static Instruction Ldc() { throw new InvalidOperationException(); }
internal static Instruction Lds_l() { throw new InvalidOperationException(); }
internal static Instruction Lds() { throw new InvalidOperationException(); }
internal static Instruction Mac_l() { throw new InvalidOperationException(); }
internal static Instruction Mac_w() { throw new InvalidOperationException(); }
internal static Instruction Mova() { throw new InvalidOperationException(); }
internal static Instruction Mov_b() { throw new InvalidOperationException(); }
internal static Instruction Mov_l() { throw new InvalidOperationException(); }
internal static Instruction Mov() { throw new InvalidOperationException(); }
internal static Instruction Movt() { throw new InvalidOperationException(); }
internal static Instruction Mov_w() { throw new InvalidOperationException(); }
internal static Instruction Mul_l() { throw new InvalidOperationException(); }
internal static Instruction Muls_w() { throw new InvalidOperationException(); }
internal static Instruction Mulu_w() { throw new InvalidOperationException(); }
internal static Instruction Negc() { throw new InvalidOperationException(); }
internal static Instruction Neg() { throw new InvalidOperationException(); }
internal static Instruction Nop() { throw new InvalidOperationException(); }
internal static Instruction Not() { throw new InvalidOperationException(); }
internal static Instruction Or_b() { throw new InvalidOperationException(); }
internal static Instruction Or() { throw new InvalidOperationException(); }
internal static Instruction Rotcl() { throw new InvalidOperationException(); }
internal static Instruction Rotcr() { throw new InvalidOperationException(); }
internal static Instruction Rotl() { throw new InvalidOperationException(); }
internal static Instruction Rotr() { throw new InvalidOperationException(); }
internal static Instruction Rte() { throw new InvalidOperationException(); }
internal static Instruction Rts() { throw new InvalidOperationException(); }
internal static Instruction Sett() { throw new InvalidOperationException(); }
internal static Instruction Shal() { throw new InvalidOperationException(); }
internal static Instruction Shar() { throw new InvalidOperationException(); }
internal static Instruction Shll16() { throw new InvalidOperationException(); }
internal static Instruction Shll2() { throw new InvalidOperationException(); }
internal static Instruction Shll8() { throw new InvalidOperationException(); }
internal static Instruction Shll() { throw new InvalidOperationException(); }
internal static Instruction Shlr16() { throw new InvalidOperationException(); }
internal static Instruction Shlr2() { throw new InvalidOperationException(); }
internal static Instruction Shlr8() { throw new InvalidOperationException(); }
internal static Instruction Shlr() { throw new InvalidOperationException(); }
internal static Instruction Sleep() { throw new InvalidOperationException(); }
internal static Instruction Stc_l() { throw new InvalidOperationException(); }
internal static Instruction Stc() { throw new InvalidOperationException(); }
internal static Instruction Sts_l() { throw new InvalidOperationException(); }
internal static Instruction Sts() { throw new InvalidOperationException(); }
internal static Instruction Subc() { throw new InvalidOperationException(); }
internal static Instruction Sub() { throw new InvalidOperationException(); }
internal static Instruction Subv() { throw new InvalidOperationException(); }
internal static Instruction Swap_b() { throw new InvalidOperationException(); }
internal static Instruction Swap_w() { throw new InvalidOperationException(); }
internal static Instruction Tas_b() { throw new InvalidOperationException(); }
internal static Instruction Trapa() { throw new InvalidOperationException(); }
internal static Instruction Tst_b() { throw new InvalidOperationException(); }
internal static Instruction Tst() { throw new InvalidOperationException(); }
internal static Instruction Word() { throw new InvalidOperationException(); }
internal static Instruction Xor_b() { throw new InvalidOperationException(); }
internal static Instruction Xor() { throw new InvalidOperationException(); }
internal static Instruction Xtrct() { throw new InvalidOperationException(); }
	}
}